import Link from "next/link";
import { ArrowLeft, Bot, CheckCircle2, Circle, ExternalLink, FileSearch, Flag, Globe2, Languages, Search, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";
import { Mascot, Particles } from "@/components/Ambient";

const modules = [
  ["Authentification Document", "Vérifie diplômes, certificats et actes officiels grâce à l’OCR et l’analyse forensique.", FileSearch],
  ["Filtre Média Intelligent", "Analyse les contenus audio et vidéo afin d’identifier les manipulations et deepfakes.", ShieldCheck],
  ["Provenance Image", "Recherche l’origine d’une image et les traces de réutilisation ou de modification.", Search],
  ["Sentinelle Linguistique", "Détecte les contenus à risque en français, camfranglais et langues locales.", Languages],
  ["Signalement Patriotique", "Permet le signalement communautaire et la qualification citoyenne des contenus suspects.", Flag],
] as const;

const stack = [["Mobile", "Flutter 3 · Dart · Provider · Dio"],["Backend", "Python 3.11 · FastAPI · OpenCV · Whisper"],["Intelligence", "CLIP · AfroXLMR · Analyse forensique"],["Données", "Supabase · PostgreSQL · Qdrant · Storage"]];

export default function DocumentationPage() {
  return <main className="min-h-screen overflow-hidden"><Particles/><header className="border-b border-white/5 bg-ink/80 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5"><Link href="/"><Logo/></Link><Link href="/" className="button-secondary"><ArrowLeft size={16}/> Retour au site</Link></div></header>
    <section className="relative border-b border-white/5 py-24"><div className="orb left-1/3 top-0"/><Mascot name="think" className="absolute right-[7%] top-8 hidden w-52 lg:block"/><div className="relative mx-auto max-w-4xl px-5"><p className="kicker">Documentation officielle · DIVLAB</p><h1 className="font-display text-5xl font-semibold tracking-[-.05em] text-white sm:text-7xl">ARGUS<br/><span className="gradient-text">Le gardien numérique citoyen</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">Toolkit mobile conçu au Cameroun contre les dérives de l’IA : deepfakes, faux documents, désinformation et manipulation linguistique.</p><div className="mt-8 flex flex-wrap gap-2">{["Flutter 3", "FastAPI", "Modèles IA spécialisés", "Projet propriétaire", "Made in Cameroon 🇨🇲"].map(x=><span className="doc-badge" key={x}>{x}</span>)}</div></div></section>
    <article className="doc-content mx-auto max-w-4xl px-5 py-20">
      <h2>Aperçu du projet</h2><p><strong>ARGUS</strong> est une application mobile développée par <strong>DIVLAB</strong>. Elle donne aux citoyens camerounais des outils simples pour vérifier, détecter, comprendre et signaler les contenus numériques suspects.</p><blockquote>Notre ambition : mettre l’intelligence artificielle au service de la souveraineté numérique, de la confiance publique et du patriotisme camerounais.</blockquote><h2>L’origine du nom ARGUS</h2><p>Argus Panoptès est le gardien aux cent yeux de la mythologie grecque. Sa vigilance ne s’interrompt jamais : certains yeux peuvent se fermer tandis que les autres restent éveillés. Le PROJET ARGUS transpose ce symbole au numérique en faisant collaborer plusieurs outils et modèles spécialisés pour observer, vérifier et protéger continuellement.</p>
      <h2>Les cinq modules citoyens</h2><div className="not-prose grid gap-4 sm:grid-cols-2">{modules.map(([title,text,Icon])=><div className="doc-module" key={title}><Icon/><h3>{title}</h3><p>{text}</p></div>)}</div>
      <h2>La couche de cyberdéfense</h2><p>Les modules d’analyse volontaire sont renforcés par trois composants transversaux qui organisent la protection réseau sans contourner HTTPS ni le chiffrement des messageries.</p><div className="not-prose grid gap-4 md:grid-cols-3"><div className="doc-module"><Globe2/><h3>Analyse réseau</h3><p>Le endpoint <code>/api/v1/network/analyze</code> attribue un score de risque explicable à une URL ou un domaine et retourne une décision ALLOW, WARN ou BLOCK.</p></div><div className="doc-module"><ShieldCheck/><h3>Protection en temps réel</h3><p>Un VPN local Android, activé avec le consentement de l’utilisateur, observe uniquement les métadonnées disponibles et applique progressivement les décisions du moteur.</p></div><div className="doc-module"><Bot/><h3>Orchestrateur IA</h3><p>Il sélectionne et séquence trois modèles spécialisés, arbitre entre règles locales et backend, puis fusionne les résultats en une décision compréhensible.</p></div></div>
      <h2>Architecture</h2><div className="architecture-flow"><div>Application Flutter</div><span>→ API sécurisée →</span><div>FastAPI + moteurs IA</div><span>→</span><div>Supabase & Qdrant</div></div>
      <h2>Stack technique</h2><div className="overflow-x-auto"><table><thead><tr><th>Couche</th><th>Technologies principales</th></tr></thead><tbody>{stack.map(([a,b])=><tr key={a}><td><strong>{a}</strong></td><td>{b}</td></tr>)}</tbody></table></div>
      <h2>Fonctionnalités phares</h2><ul><li>Interface mobile Liquid Glass moderne et accessible.</li><li>Analyse automatique d’un contenu partagé depuis WhatsApp ou la galerie.</li><li>Mode démonstration permettant d’explorer les cinq modules sans backend.</li><li>Approche adaptée au français, au camfranglais et aux réalités locales.</li><li>Signalement patriotique destiné à renforcer la résilience collective.</li></ul>
      <h2>État d’avancement</h2><div className="space-y-3">{[[true,"Application Flutter et cinq parcours fonctionnels"],[true,"Mode démonstration et partage Android/iOS"],[true,"Architecture frontend et services"],[false,"Connexion complète des modèles IA"],[false,"Déploiement public du backend"],[false,"Publication sur les stores"]].map(([ok,text])=><div className="flex items-center gap-3" key={String(text)}>{ok?<CheckCircle2 className="text-cyan"/>:<Circle className="text-slate-600"/>}<span>{text}</span></div>)}</div>
      <h2>Confidentialité et accès au code</h2><blockquote>ARGUS est un projet propriétaire de DIVLAB. Son dépôt, son architecture détaillée et ses mécanismes de défense ne sont pas accessibles publiquement.</blockquote><p>Un accès technique peut être accordé uniquement aux personnes autorisées dans le cadre d’une évaluation, d’un audit ou d’un partenariat, sous les conditions définies par DIVLAB. Cette politique protège la propriété intellectuelle du projet et limite l’exposition de composants sensibles pouvant être contournés ou détournés.</p>
      <h2>À propos de DIVLAB</h2><p>DIVLAB est un laboratoire camerounais d’innovation numérique. ARGUS traduit sa volonté de construire des technologies utiles, responsables et ancrées dans les enjeux du pays.</p><a href="https://divlabs-tech.com" target="_blank" rel="noreferrer" className="button-primary not-prose mt-5">Découvrir DIVLAB <ExternalLink size={16}/></a>
    </article><footer className="border-t border-white/5 py-10 text-center text-sm text-slate-600">PROJET ARGUS — une initiative DIVLAB · Cameroun 🇨🇲</footer>
  </main>;
}
